### PR TITLE
RoomDTO, RoomFacade, RoomService implemented

### PR DESCRIPTION
**Pull request by Dominick1993**

### CODE REVIEW

**Comment by Dominick1993** [comment]
RoomFacadeImpl is not implemented, will fix soon™

**Comment by Dominick1993** [comment]
Ready for review

**Comment by vasekstebra** [comment]
Looks good to me. I would maybe add a new function to facade / service findAvailableRoomsForHotel that would return all rooms that are not reserved in a certain time period. This could serve as one of the two "non-trivial" business functions. We can discuss this on the seminar.

**Comment by Dominick1993** [comment]
I won't be attending the seminar, again... I am willing to implement the method you recommended if all of you find it "complex" enough to fulfill the requirement (and I'll probably implement it anyway)

**Comment by vasekstebra** [comment]
Ok, thanks.

**Comment by Dominick1993** [comment]
Merged with master, features implemented to fulfill requirements, proposed `findAvailableRoomsForHotel(...)` business method was not implemented, because I think it should be part of `ReservationService`, which we will hopefully discuss.

**Pull request merged**
